clear all

% plotting data from the NeutronCode
data = csvread('C:/Users/Mark/Dropbox/Projecten/NeutronCode/DATA.csv');
data_c = csvread('C:/Users/Mark/Dropbox/Projecten/NeutronCode/DATA_cross_sections.csv');

% r,data.phi[r],data.ParticleEnergy[r],data.f[r],data.g[0][r],data.A[r]
% figure %potential
% potential = plot(data(:,1),data(:,2))
% legend(potential, 'Phi')
% figure %particle energies
% energies = plot(data(:,1),data(:,3))
% legend(energies, 'E')
% figure
% surfival = plot(data_c(:,1),data_c(:,2))
% legend(surfival, 'SIIEE')
% figure
% surfival = plot(data(:,1),data(:,4),data(:,1),data(:,5))
% legend(surfival, 'f(r)', 'g(r,r1)')
figure
cross = loglog(data_c(:,1),data_c(:,2),data_c(:,1),data_c(:,3),data_c(:,1),data_c(:,4))
legend(cross, 'CX','Ion','Tot')

% 
% , ...
%      data(:,3),data(:,4), ...
%      data(:,5),data(:,6), ...
%      data(:,7),data(:,8), ...
%      data(:,9),data(:,10), ...
%      data(:,11),data(:,12), ...
%      data(:,13),data(:,14), ...
%      data(:,15),data(:,16), ...
%      data(:,17),data(:,18), ...
%      data(:,19),data(:,20), ...
%      data(:,21),data(:,22), ...
%      data(:,23),data(:,24), ...
%      data(:,25),data(:,26), ...
%      data(:,27),data(:,28), ...
%      data(:,29),data(:,30))
